### ISSUE TITLE
请教下，bert4keras是哪个版本？

### ISSUE THREAD

**Issue by sshimii** [fushengwuyu/correction_keras#2]
from bert4keras.tokenizers import load_vocab, Tokenizer

我0.7.0版本，使用这两个函数时
提示load_vocab 无startswith参数
以及tokenizer没有_token_mask_id，_token_end_id

**Comment by fushengwuyu** [comment]
你试试最新的版本呢，具体哪个版本我忘记了，我现在也更新为最新版本了发自我的华为手机-------- 原始邮件 --------发件人： shimii <notifications@github.com>日期： 2020年10月13日周二 14:53收件人： fushengwuyu/chinese_spelling_correction <chinese_spelling_correction@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [fushengwuyu/chinese_spelling_correction] 请教下，bert4keras是哪个版本？ (#2)

from bert4keras.tokenizers import load_vocab, Tokenizer

我0.7.0版本，使用这两个函数时

提示load_vocab 无startswith参数

以及tokenizer没有_token_mask_id，_token_end_id

**Comment by sshimii** [comment]
谢谢大佬，运行没问题了
